% |\      /|  ** The International PEPA compiler:
% | \    / |  ipc v0.99
% |  \  /  |  Produced on location in/between Edinburgh, 
% |   \/   |  Leeds, London, Ludlow, Lucca and Sophia-Antipolis
% |   <>   |  2002-8
% |   /\   |  Contributors:
% |  /  \  |      Jeremy Bradley, Allan Clark,
% | /    \ |      Stephen Gilmore and Fragkiskos Gounelas
% |/      \|  Queries or problems: a.d.clark@ed.ac.uk
% 
% This file was generated by ipc
% from the following pepa model

\model{




\statevector{
\type{ short }{ P1_2
 , P2_2
 , P1
 , P2
 , yyMasterProbeRunning
 , yyMasterProbeStopped
 , yyPassageProbeRunning
 , yyPassageProbeStopped }

}

\initial{
P1_2 = 1 ;
P2_2 = 0 ;
P1 = 1 ;
P2 = 0 ;
yyMasterProbeRunning = 0 ;
yyMasterProbeStopped = 1 ;
yyPassageProbeRunning = 0 ;
yyPassageProbeStopped = 1 ;

}

\transition{ trans_1_0 }
{
% a

\condition{ (P1_2 == 1) && (P1 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P1 = 0 ;
next -> yyMasterProbeStopped = 0 ;
next -> yyPassageProbeStopped = 0 ;
next -> P1_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeRunning = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_1_1 }
{
% a

\condition{ (P1_2 == 1) && (P1 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P1_2 = 0 ;
next -> yyMasterProbeStopped = 0 ;
next -> yyPassageProbeStopped = 0 ;
next -> P2_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeRunning = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_2_0 }
{
% a

\condition{ (P2_2 == 1) && (P1 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P1 = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P2_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_2_1 }
{
% b

\condition{ (P2_2 == 1) && (P1 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P2_2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P1_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_5_0 }
{
% a

\condition{ (P2_2 == 1) && (P1 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P1 = 0 ;
next -> yyMasterProbeStopped = 0 ;
next -> yyPassageProbeStopped = 0 ;
next -> P2_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeRunning = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_5_1 }
{
% b

\condition{ (P2_2 == 1) && (P1 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P2_2 = 0 ;
next -> P1_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_3_0 }
{
% a

\condition{ (P1_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P1_2 = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P2_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_3_1 }
{
% b

\condition{ (P1_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P1_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_6_0 }
{
% a

\condition{ (P1_2 == 1) && (P2 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P1_2 = 0 ;
next -> yyMasterProbeStopped = 0 ;
next -> yyPassageProbeStopped = 0 ;
next -> P2_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeRunning = 1 ;
next -> yyPassageProbeRunning = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_6_1 }
{
% b

\condition{ (P1_2 == 1) && (P2 == 1) && (yyMasterProbeStopped == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P2 = 0 ;
next -> P1_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_7_0 }
{
% b

\condition{ (P2_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P2_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_7_1 }
{
% b

\condition{ (P2_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeRunning == 1) }
\action{
next -> P2_2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> yyPassageProbeRunning = 0 ;
next -> P1_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_4_0 }
{
% b

\condition{ (P2_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> P2_2 = 1 ;
next -> P1 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}

\transition{ trans_4_1 }
{
% b

\condition{ (P2_2 == 1) && (P2 == 1) && (yyMasterProbeRunning == 1) && (yyPassageProbeStopped == 1) }
\action{
next -> P2_2 = 0 ;
next -> yyMasterProbeRunning = 0 ;
next -> P1_2 = 1 ;
next -> P2 = 1 ;
next -> yyMasterProbeStopped = 1 ;
next -> yyPassageProbeStopped = 1 ;

}

\rate{ 1 }
\priority{1}
}



}

\solution{ 
\method{ automatic }
}

\passage{
\sourcecondition{ yyPassageProbeRunning }
\targetcondition{ yyMasterProbeStopped }
\t_start{ 0.5 }
\t_stop{ 10.0 }
\t_step{ 0.1 }
}

